name: Castor setup
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test Castor setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: pyrech/setup-php@7ce22e0264b6c4bb45f88456d0d5dc64c75b77d9
        with:
          php-version: '8.1'
          tools: castor

      - name: Run castor "hello" task
        run: castor hello
